[package]
name = "hexlife"
version = "0.1.0"
authors = ["petrak@ <petrathekat@gmail.com>"]

edition = "2021"

[dependencies]
ahash = "0.8.2"
enumflags2 = "0.7.5"
hex2d = "1.1.0"

[workspace]
members = ["viewer"]

[profile.dev.package.'*']
opt-level = 3
